### ISSUE TITLE
[Question] A way to receive events from the panned & zoomed element?

### ISSUE THREAD

**Issue by janseris** [shaigem/BlazorPanzoom#13]
Hi, thanks for this awesome tool.
I am having problems with catching events from the element which has  @ref="@context.ElementReference" - the panned and zoomed element.
Is there any way to handle onclick (and all other events) from that element?

Thank you

**Comment by ajitpal2311** [comment]
I am having similar problem @janseris @shaigem . I am using pan zoom component for a div which contains img and an overlaying canvas and I want handle mouse events on the canvas but apparently panzoom blocks it. How did you solve this problem?
